name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Hello-World:
    runs-on: ubuntu-latest
    steps:
      -  run: echo "Hello This is My github workflow"
  Next-Hello-World:
    runs-on: ubuntu-latest
    steps:
      - run : echo "This is next Hello World"
  Show-Python-Program:
    runs-on: ubuntu-latest
    steps:
      - run : cat main.py

